/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/0CTF-2016-piapiapia': RouteRecordInfo<'/posts/0CTF-2016-piapiapia', '/posts/0CTF-2016-piapiapia', Record<never, never>, Record<never, never>>,
    '/posts/2020-新春红包题-1': RouteRecordInfo<'/posts/2020-新春红包题-1', '/posts/2020-新春红包题-1', Record<never, never>, Record<never, never>>,
    '/posts/2021祥云杯-Package-Manager-2021': RouteRecordInfo<'/posts/2021祥云杯-Package-Manager-2021', '/posts/2021祥云杯-Package-Manager-2021', Record<never, never>, Record<never, never>>,
    '/posts/2021祥云杯-secrets-of-admin': RouteRecordInfo<'/posts/2021祥云杯-secrets-of-admin', '/posts/2021祥云杯-secrets-of-admin', Record<never, never>, Record<never, never>>,
    '/posts/2024-NSS秋季赛': RouteRecordInfo<'/posts/2024-NSS秋季赛', '/posts/2024-NSS秋季赛', Record<never, never>, Record<never, never>>,
    '/posts/2024国城杯部分wp': RouteRecordInfo<'/posts/2024国城杯部分wp', '/posts/2024国城杯部分wp', Record<never, never>, Record<never, never>>,
    '/posts/aliyunctf2025': RouteRecordInfo<'/posts/aliyunctf2025', '/posts/aliyunctf2025', Record<never, never>, Record<never, never>>,
    '/posts/b01lers2020-Life-on-Mars': RouteRecordInfo<'/posts/b01lers2020-Life-on-Mars', '/posts/b01lers2020-Life-on-Mars', Record<never, never>, Record<never, never>>,
    '/posts/b01lers2020-Scrambled': RouteRecordInfo<'/posts/b01lers2020-Scrambled', '/posts/b01lers2020-Scrambled', Record<never, never>, Record<never, never>>,
    '/posts/b01lers2020-Welcome-to-Earth': RouteRecordInfo<'/posts/b01lers2020-Welcome-to-Earth', '/posts/b01lers2020-Welcome-to-Earth', Record<never, never>, Record<never, never>>,
    '/posts/Basectf': RouteRecordInfo<'/posts/Basectf', '/posts/Basectf', Record<never, never>, Record<never, never>>,
    '/posts/bestphp-s-revenge': RouteRecordInfo<'/posts/bestphp-s-revenge', '/posts/bestphp-s-revenge', Record<never, never>, Record<never, never>>,
    '/posts/BJDCTF2020-EzPHP': RouteRecordInfo<'/posts/BJDCTF2020-EzPHP', '/posts/BJDCTF2020-EzPHP', Record<never, never>, Record<never, never>>,
    '/posts/Black-Watch-入群题-Web': RouteRecordInfo<'/posts/Black-Watch-入群题-Web', '/posts/Black-Watch-入群题-Web', Record<never, never>, Record<never, never>>,
    '/posts/blog奇葩问题组合': RouteRecordInfo<'/posts/blog奇葩问题组合', '/posts/blog奇葩问题组合', Record<never, never>, Record<never, never>>,
    '/posts/BSidesCF-2019-Mixer': RouteRecordInfo<'/posts/BSidesCF-2019-Mixer', '/posts/BSidesCF-2019-Mixer', Record<never, never>, Record<never, never>>,
    '/posts/BSidesCF-2019-Pick-Tac-Toe': RouteRecordInfo<'/posts/BSidesCF-2019-Pick-Tac-Toe', '/posts/BSidesCF-2019-Pick-Tac-Toe', Record<never, never>, Record<never, never>>,
    '/posts/BSidesCF-2019-Sequel': RouteRecordInfo<'/posts/BSidesCF-2019-Sequel', '/posts/BSidesCF-2019-Sequel', Record<never, never>, Record<never, never>>,
    '/posts/BSidesCF-2019-SVGMagic': RouteRecordInfo<'/posts/BSidesCF-2019-SVGMagic', '/posts/BSidesCF-2019-SVGMagic', Record<never, never>, Record<never, never>>,
    '/posts/BSidesCF-2020-Cards': RouteRecordInfo<'/posts/BSidesCF-2020-Cards', '/posts/BSidesCF-2020-Cards', Record<never, never>, Record<never, never>>,
    '/posts/BSidesCF-2020-Hurdles': RouteRecordInfo<'/posts/BSidesCF-2020-Hurdles', '/posts/BSidesCF-2020-Hurdles', Record<never, never>, Record<never, never>>,
    '/posts/BuildCTF': RouteRecordInfo<'/posts/BuildCTF', '/posts/BuildCTF', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-华东北赛区-Web2': RouteRecordInfo<'/posts/CISCN2019-华东北赛区-Web2', '/posts/CISCN2019-华东北赛区-Web2', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-华东南赛区-Double-Secret': RouteRecordInfo<'/posts/CISCN2019-华东南赛区-Double-Secret', '/posts/CISCN2019-华东南赛区-Double-Secret', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-华东南赛区-Web4': RouteRecordInfo<'/posts/CISCN2019-华东南赛区-Web4', '/posts/CISCN2019-华东南赛区-Web4', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-华北赛区-Day1-Web1-Dropbox': RouteRecordInfo<'/posts/CISCN2019-华北赛区-Day1-Web1-Dropbox', '/posts/CISCN2019-华北赛区-Day1-Web1-Dropbox', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-华北赛区-Day1-Web2-ikun': RouteRecordInfo<'/posts/CISCN2019-华北赛区-Day1-Web2-ikun', '/posts/CISCN2019-华北赛区-Day1-Web2-ikun', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-华北赛区-Day1-Web5-CyberPunk': RouteRecordInfo<'/posts/CISCN2019-华北赛区-Day1-Web5-CyberPunk', '/posts/CISCN2019-华北赛区-Day1-Web5-CyberPunk', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-总决赛-Day1-Web4-Laravel1': RouteRecordInfo<'/posts/CISCN2019-总决赛-Day1-Web4-Laravel1', '/posts/CISCN2019-总决赛-Day1-Web4-Laravel1', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2019-总决赛-Day2-Web1-Easyweb': RouteRecordInfo<'/posts/CISCN2019-总决赛-Day2-Web1-Easyweb', '/posts/CISCN2019-总决赛-Day2-Web1-Easyweb', Record<never, never>, Record<never, never>>,
    '/posts/CISCN2021-Quals-upload': RouteRecordInfo<'/posts/CISCN2021-Quals-upload', '/posts/CISCN2021-Quals-upload', Record<never, never>, Record<never, never>>,
    '/posts/crypto': RouteRecordInfo<'/posts/crypto', '/posts/crypto', Record<never, never>, Record<never, never>>,
    '/posts/crypto-1': RouteRecordInfo<'/posts/crypto-1', '/posts/crypto-1', Record<never, never>, Record<never, never>>,
    '/posts/crypto-AES-DES': RouteRecordInfo<'/posts/crypto-AES-DES', '/posts/crypto-AES-DES', Record<never, never>, Record<never, never>>,
    '/posts/crypto-ECC加密': RouteRecordInfo<'/posts/crypto-ECC加密', '/posts/crypto-ECC加密', Record<never, never>, Record<never, never>>,
    '/posts/crypto-rsa': RouteRecordInfo<'/posts/crypto-rsa', '/posts/crypto-rsa', Record<never, never>, Record<never, never>>,
    '/posts/crypto-suanfa': RouteRecordInfo<'/posts/crypto-suanfa', '/posts/crypto-suanfa', Record<never, never>, Record<never, never>>,
    '/posts/CSAWQual-2016-i-got-id': RouteRecordInfo<'/posts/CSAWQual-2016-i-got-id', '/posts/CSAWQual-2016-i-got-id', Record<never, never>, Record<never, never>>,
    '/posts/CSAWQual-2019-Web-Unagi': RouteRecordInfo<'/posts/CSAWQual-2019-Web-Unagi', '/posts/CSAWQual-2019-Web-Unagi', Record<never, never>, Record<never, never>>,
    '/posts/CSCCTF-2019-Qual-FlaskLight': RouteRecordInfo<'/posts/CSCCTF-2019-Qual-FlaskLight', '/posts/CSCCTF-2019-Qual-FlaskLight', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-java': RouteRecordInfo<'/posts/ctfshow-java', '/posts/ctfshow-java', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-php特性': RouteRecordInfo<'/posts/ctfshow-php特性', '/posts/ctfshow-php特性', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-ssrf': RouteRecordInfo<'/posts/ctfshow-ssrf', '/posts/ctfshow-ssrf', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-ssti': RouteRecordInfo<'/posts/ctfshow-ssti', '/posts/ctfshow-ssti', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-xss': RouteRecordInfo<'/posts/ctfshow-xss', '/posts/ctfshow-xss', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-xxe': RouteRecordInfo<'/posts/ctfshow-xxe', '/posts/ctfshow-xxe', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-信息搜集': RouteRecordInfo<'/posts/ctfshow-信息搜集', '/posts/ctfshow-信息搜集', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-命令执行': RouteRecordInfo<'/posts/ctfshow-命令执行', '/posts/ctfshow-命令执行', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-常用姿势': RouteRecordInfo<'/posts/ctfshow-常用姿势', '/posts/ctfshow-常用姿势', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow-文件上传': RouteRecordInfo<'/posts/ctfshow-文件上传', '/posts/ctfshow-文件上传', Record<never, never>, Record<never, never>>,
    '/posts/ctfshow文件包含': RouteRecordInfo<'/posts/ctfshow文件包含', '/posts/ctfshow文件包含', Record<never, never>, Record<never, never>>,
    '/posts/DDCTF-2019-homebrew-event-loop': RouteRecordInfo<'/posts/DDCTF-2019-homebrew-event-loop', '/posts/DDCTF-2019-homebrew-event-loop', Record<never, never>, Record<never, never>>,
    '/posts/De1CTF-2019-Giftbox': RouteRecordInfo<'/posts/De1CTF-2019-Giftbox', '/posts/De1CTF-2019-Giftbox', Record<never, never>, Record<never, never>>,
    '/posts/De1CTF-2019-ShellShellShell': RouteRecordInfo<'/posts/De1CTF-2019-ShellShellShell', '/posts/De1CTF-2019-ShellShellShell', Record<never, never>, Record<never, never>>,
    '/posts/Dest0g3-520迎新赛-EasySSTI': RouteRecordInfo<'/posts/Dest0g3-520迎新赛-EasySSTI', '/posts/Dest0g3-520迎新赛-EasySSTI', Record<never, never>, Record<never, never>>,
    '/posts/Dest0g3-520迎新赛-SimpleRCE': RouteRecordInfo<'/posts/Dest0g3-520迎新赛-SimpleRCE', '/posts/Dest0g3-520迎新赛-SimpleRCE', Record<never, never>, Record<never, never>>,
    '/posts/EasyBypass': RouteRecordInfo<'/posts/EasyBypass', '/posts/EasyBypass', Record<never, never>, Record<never, never>>,
    '/posts/EIS-2019-EzPOP': RouteRecordInfo<'/posts/EIS-2019-EzPOP', '/posts/EIS-2019-EzPOP', Record<never, never>, Record<never, never>>,
    '/posts/FBCTF2019-Event': RouteRecordInfo<'/posts/FBCTF2019-Event', '/posts/FBCTF2019-Event', Record<never, never>, Record<never, never>>,
    '/posts/FBCTF2019-Products-Manager': RouteRecordInfo<'/posts/FBCTF2019-Products-Manager', '/posts/FBCTF2019-Products-Manager', Record<never, never>, Record<never, never>>,
    '/posts/FBCTF2019-RCEService': RouteRecordInfo<'/posts/FBCTF2019-RCEService', '/posts/FBCTF2019-RCEService', Record<never, never>, Record<never, never>>,
    '/posts/FireshellCTF2020-Caas': RouteRecordInfo<'/posts/FireshellCTF2020-Caas', '/posts/FireshellCTF2020-Caas', Record<never, never>, Record<never, never>>,
    '/posts/FireshellCTF2020-ScreenShooter': RouteRecordInfo<'/posts/FireshellCTF2020-ScreenShooter', '/posts/FireshellCTF2020-ScreenShooter', Record<never, never>, Record<never, never>>,
    '/posts/FireshellCTF2020-URL-TO-PDF': RouteRecordInfo<'/posts/FireshellCTF2020-URL-TO-PDF', '/posts/FireshellCTF2020-URL-TO-PDF', Record<never, never>, Record<never, never>>,
    '/posts/GHCTF2025': RouteRecordInfo<'/posts/GHCTF2025', '/posts/GHCTF2025', Record<never, never>, Record<never, never>>,
    '/posts/GKCTF-2021-babycat-revenge': RouteRecordInfo<'/posts/GKCTF-2021-babycat-revenge', '/posts/GKCTF-2021-babycat-revenge', Record<never, never>, Record<never, never>>,
    '/posts/GKCTF-2021-CheckBot': RouteRecordInfo<'/posts/GKCTF-2021-CheckBot', '/posts/GKCTF-2021-CheckBot', Record<never, never>, Record<never, never>>,
    '/posts/GKCTF-2021-easycms': RouteRecordInfo<'/posts/GKCTF-2021-easycms', '/posts/GKCTF-2021-easycms', Record<never, never>, Record<never, never>>,
    '/posts/GKCTF2020-cve版签到': RouteRecordInfo<'/posts/GKCTF2020-cve版签到', '/posts/GKCTF2020-cve版签到', Record<never, never>, Record<never, never>>,
    '/posts/GoogleCTF2019-Quals-Bnv': RouteRecordInfo<'/posts/GoogleCTF2019-Quals-Bnv', '/posts/GoogleCTF2019-Quals-Bnv', Record<never, never>, Record<never, never>>,
    '/posts/GWCTF-2019-mypassword': RouteRecordInfo<'/posts/GWCTF-2019-mypassword', '/posts/GWCTF-2019-mypassword', Record<never, never>, Record<never, never>>,
    '/posts/GWCTF-2019-你的名字': RouteRecordInfo<'/posts/GWCTF-2019-你的名字', '/posts/GWCTF-2019-你的名字', Record<never, never>, Record<never, never>>,
    '/posts/GWCTF-2019-枯燥的抽奖': RouteRecordInfo<'/posts/GWCTF-2019-枯燥的抽奖', '/posts/GWCTF-2019-枯燥的抽奖', Record<never, never>, Record<never, never>>,
    '/posts/GXYCTF2019-BabysqliV3-0': RouteRecordInfo<'/posts/GXYCTF2019-BabysqliV3-0', '/posts/GXYCTF2019-BabysqliV3-0', Record<never, never>, Record<never, never>>,
    '/posts/GXYCTF2019-StrongestMind': RouteRecordInfo<'/posts/GXYCTF2019-StrongestMind', '/posts/GXYCTF2019-StrongestMind', Record<never, never>, Record<never, never>>,
    '/posts/GYCTF2020-Easyphp': RouteRecordInfo<'/posts/GYCTF2020-Easyphp', '/posts/GYCTF2020-Easyphp', Record<never, never>, Record<never, never>>,
    '/posts/GYCTF2020-EasyThinking': RouteRecordInfo<'/posts/GYCTF2020-EasyThinking', '/posts/GYCTF2020-EasyThinking', Record<never, never>, Record<never, never>>,
    '/posts/GYCTF2020-Ez-Express': RouteRecordInfo<'/posts/GYCTF2020-Ez-Express', '/posts/GYCTF2020-Ez-Express', Record<never, never>, Record<never, never>>,
    '/posts/GYCTF2020-Ezsqli': RouteRecordInfo<'/posts/GYCTF2020-Ezsqli', '/posts/GYCTF2020-Ezsqli', Record<never, never>, Record<never, never>>,
    '/posts/GYCTF2020-FlaskApp': RouteRecordInfo<'/posts/GYCTF2020-FlaskApp', '/posts/GYCTF2020-FlaskApp', Record<never, never>, Record<never, never>>,
    '/posts/GYCTF2020-Node-Game-1': RouteRecordInfo<'/posts/GYCTF2020-Node-Game-1', '/posts/GYCTF2020-Node-Game-1', Record<never, never>, Record<never, never>>,
    '/posts/HarekazeCTF2019-Avatar-Uploader-1': RouteRecordInfo<'/posts/HarekazeCTF2019-Avatar-Uploader-1', '/posts/HarekazeCTF2019-Avatar-Uploader-1', Record<never, never>, Record<never, never>>,
    '/posts/HarekazeCTF2019-Easy-Notes': RouteRecordInfo<'/posts/HarekazeCTF2019-Easy-Notes', '/posts/HarekazeCTF2019-Easy-Notes', Record<never, never>, Record<never, never>>,
    '/posts/HarekazeCTF2019-encode-and-encode': RouteRecordInfo<'/posts/HarekazeCTF2019-encode-and-encode', '/posts/HarekazeCTF2019-encode-and-encode', Record<never, never>, Record<never, never>>,
    '/posts/HarekazeCTF2019-Sqlite-Voting': RouteRecordInfo<'/posts/HarekazeCTF2019-Sqlite-Voting', '/posts/HarekazeCTF2019-Sqlite-Voting', Record<never, never>, Record<never, never>>,
    '/posts/HCTF-2018-Hideandseek': RouteRecordInfo<'/posts/HCTF-2018-Hideandseek', '/posts/HCTF-2018-Hideandseek', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/HFCTF-2021-Final-easyflask': RouteRecordInfo<'/posts/HFCTF-2021-Final-easyflask', '/posts/HFCTF-2021-Final-easyflask', Record<never, never>, Record<never, never>>,
    '/posts/HFCTF-2021-Final-hatenum': RouteRecordInfo<'/posts/HFCTF-2021-Final-hatenum', '/posts/HFCTF-2021-Final-hatenum', Record<never, never>, Record<never, never>>,
    '/posts/HFCTF2020-BabyUpload': RouteRecordInfo<'/posts/HFCTF2020-BabyUpload', '/posts/HFCTF2020-BabyUpload', Record<never, never>, Record<never, never>>,
    '/posts/HFCTF2020-EasyLogin': RouteRecordInfo<'/posts/HFCTF2020-EasyLogin', '/posts/HFCTF2020-EasyLogin', Record<never, never>, Record<never, never>>,
    '/posts/HFCTF2020-JustEscape': RouteRecordInfo<'/posts/HFCTF2020-JustEscape', '/posts/HFCTF2020-JustEscape', Record<never, never>, Record<never, never>>,
    '/posts/HFCTF2021-Quals-Unsetme': RouteRecordInfo<'/posts/HFCTF2021-Quals-Unsetme', '/posts/HFCTF2021-Quals-Unsetme', Record<never, never>, Record<never, never>>,
    '/posts/HITCON-2016-Leaking': RouteRecordInfo<'/posts/HITCON-2016-Leaking', '/posts/HITCON-2016-Leaking', Record<never, never>, Record<never, never>>,
    '/posts/HITCON-2017-SSRFme': RouteRecordInfo<'/posts/HITCON-2017-SSRFme', '/posts/HITCON-2017-SSRFme', Record<never, never>, Record<never, never>>,
    '/posts/HMGCTF2022-Fan-Website': RouteRecordInfo<'/posts/HMGCTF2022-Fan-Website', '/posts/HMGCTF2022-Fan-Website', Record<never, never>, Record<never, never>>,
    '/posts/HMGCTF2022-Smarty-Calculator': RouteRecordInfo<'/posts/HMGCTF2022-Smarty-Calculator', '/posts/HMGCTF2022-Smarty-Calculator', Record<never, never>, Record<never, never>>,
    '/posts/HNCTF-2022-WEEK2-ez-ssrf': RouteRecordInfo<'/posts/HNCTF-2022-WEEK2-ez-ssrf', '/posts/HNCTF-2022-WEEK2-ez-ssrf', Record<never, never>, Record<never, never>>,
    '/posts/HNCTF-2022-WEEK4-unf1ni3hed-web3he1': RouteRecordInfo<'/posts/HNCTF-2022-WEEK4-unf1ni3hed-web3he1', '/posts/HNCTF-2022-WEEK4-unf1ni3hed-web3he1', Record<never, never>, Record<never, never>>,
    '/posts/HTML学习篇': RouteRecordInfo<'/posts/HTML学习篇', '/posts/HTML学习篇', Record<never, never>, Record<never, never>>,
    '/posts/HXBCTF-2021-easywill': RouteRecordInfo<'/posts/HXBCTF-2021-easywill', '/posts/HXBCTF-2021-easywill', Record<never, never>, Record<never, never>>,
    '/posts/isctf2024 web': RouteRecordInfo<'/posts/isctf2024 web', '/posts/isctf2024 web', Record<never, never>, Record<never, never>>,
    '/posts/isctf2024-crypto': RouteRecordInfo<'/posts/isctf2024-crypto', '/posts/isctf2024-crypto', Record<never, never>, Record<never, never>>,
    '/posts/ISITDTU-2019-EasyPHP': RouteRecordInfo<'/posts/ISITDTU-2019-EasyPHP', '/posts/ISITDTU-2019-EasyPHP', Record<never, never>, Record<never, never>>,
    '/posts/Java': RouteRecordInfo<'/posts/Java', '/posts/Java', Record<never, never>, Record<never, never>>,
    '/posts/java-sec-code': RouteRecordInfo<'/posts/java-sec-code', '/posts/java-sec-code', Record<never, never>, Record<never, never>>,
    '/posts/Javaweb': RouteRecordInfo<'/posts/Javaweb', '/posts/Javaweb', Record<never, never>, Record<never, never>>,
    '/posts/java反序列化': RouteRecordInfo<'/posts/java反序列化', '/posts/java反序列化', Record<never, never>, Record<never, never>>,
    '/posts/JMCTF-2021-GoOSS': RouteRecordInfo<'/posts/JMCTF-2021-GoOSS', '/posts/JMCTF-2021-GoOSS', Record<never, never>, Record<never, never>>,
    '/posts/JMCTF-2021-UploadHub': RouteRecordInfo<'/posts/JMCTF-2021-UploadHub', '/posts/JMCTF-2021-UploadHub', Record<never, never>, Record<never, never>>,
    '/posts/LineCTF2022-BB': RouteRecordInfo<'/posts/LineCTF2022-BB', '/posts/LineCTF2022-BB', Record<never, never>, Record<never, never>>,
    '/posts/LineCTF2022-gotm': RouteRecordInfo<'/posts/LineCTF2022-gotm', '/posts/LineCTF2022-gotm', Record<never, never>, Record<never, never>>,
    '/posts/md5': RouteRecordInfo<'/posts/md5', '/posts/md5', Record<never, never>, Record<never, never>>,
    '/posts/misc': RouteRecordInfo<'/posts/misc', '/posts/misc', Record<never, never>, Record<never, never>>,
    '/posts/MoeCTF': RouteRecordInfo<'/posts/MoeCTF', '/posts/MoeCTF', Record<never, never>, Record<never, never>>,
    '/posts/MoeCTF-2025': RouteRecordInfo<'/posts/MoeCTF-2025', '/posts/MoeCTF-2025', Record<never, never>, Record<never, never>>,
    '/posts/MRCTF2020-Ezaudit': RouteRecordInfo<'/posts/MRCTF2020-Ezaudit', '/posts/MRCTF2020-Ezaudit', Record<never, never>, Record<never, never>>,
    '/posts/MRCTF2020-Ezpop-Revenge': RouteRecordInfo<'/posts/MRCTF2020-Ezpop-Revenge', '/posts/MRCTF2020-Ezpop-Revenge', Record<never, never>, Record<never, never>>,
    '/posts/MRCTF2020套娃': RouteRecordInfo<'/posts/MRCTF2020套娃', '/posts/MRCTF2020套娃', Record<never, never>, Record<never, never>>,
    '/posts/MySQL学习': RouteRecordInfo<'/posts/MySQL学习', '/posts/MySQL学习', Record<never, never>, Record<never, never>>,
    '/posts/N1CTF-2018-eating-cms': RouteRecordInfo<'/posts/N1CTF-2018-eating-cms', '/posts/N1CTF-2018-eating-cms', Record<never, never>, Record<never, never>>,
    '/posts/NCTF-2024': RouteRecordInfo<'/posts/NCTF-2024', '/posts/NCTF-2024', Record<never, never>, Record<never, never>>,
    '/posts/NCTF2019-SQLi': RouteRecordInfo<'/posts/NCTF2019-SQLi', '/posts/NCTF2019-SQLi', Record<never, never>, Record<never, never>>,
    '/posts/NCTF2019-True-XML-cookbook': RouteRecordInfo<'/posts/NCTF2019-True-XML-cookbook', '/posts/NCTF2019-True-XML-cookbook', Record<never, never>, Record<never, never>>,
    '/posts/NESTCTF-2019-Love-Math-2': RouteRecordInfo<'/posts/NESTCTF-2019-Love-Math-2', '/posts/NESTCTF-2019-Love-Math-2', Record<never, never>, Record<never, never>>,
    '/posts/new-star-CTF': RouteRecordInfo<'/posts/new-star-CTF', '/posts/new-star-CTF', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-Begin-of-HTTP': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-Begin-of-HTTP', '/posts/NewStarCTF-2023-公开赛道-Begin-of-HTTP', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-EasyLogin': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-EasyLogin', '/posts/NewStarCTF-2023-公开赛道-EasyLogin', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-ez-sql': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-ez-sql', '/posts/NewStarCTF-2023-公开赛道-ez-sql', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-Include-🍐': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-Include-🍐', '/posts/NewStarCTF-2023-公开赛道-Include-🍐', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-include-0。0': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-include-0。0', '/posts/NewStarCTF-2023-公开赛道-include-0。0', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-midsql': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-midsql', '/posts/NewStarCTF-2023-公开赛道-midsql', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-POP-Gadget': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-POP-Gadget', '/posts/NewStarCTF-2023-公开赛道-POP-Gadget', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-R-C-E': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-R-C-E', '/posts/NewStarCTF-2023-公开赛道-R-C-E', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-泄漏的秘密': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-泄漏的秘密', '/posts/NewStarCTF-2023-公开赛道-泄漏的秘密', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-2023-公开赛道-逃': RouteRecordInfo<'/posts/NewStarCTF-2023-公开赛道-逃', '/posts/NewStarCTF-2023-公开赛道-逃', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-公开赛赛道-BabySSTI-Three': RouteRecordInfo<'/posts/NewStarCTF-公开赛赛道-BabySSTI-Three', '/posts/NewStarCTF-公开赛赛道-BabySSTI-Three', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-公开赛赛道-BabySSTI-Two': RouteRecordInfo<'/posts/NewStarCTF-公开赛赛道-BabySSTI-Two', '/posts/NewStarCTF-公开赛赛道-BabySSTI-Two', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-公开赛赛道-So-Baby-RCE': RouteRecordInfo<'/posts/NewStarCTF-公开赛赛道-So-Baby-RCE', '/posts/NewStarCTF-公开赛赛道-So-Baby-RCE', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-公开赛赛道-So-Baby-RCE-Again': RouteRecordInfo<'/posts/NewStarCTF-公开赛赛道-So-Baby-RCE-Again', '/posts/NewStarCTF-公开赛赛道-So-Baby-RCE-Again', Record<never, never>, Record<never, never>>,
    '/posts/NewStarCTF-公开赛赛道-UnserializeOne': RouteRecordInfo<'/posts/NewStarCTF-公开赛赛道-UnserializeOne', '/posts/NewStarCTF-公开赛赛道-UnserializeOne', Record<never, never>, Record<never, never>>,
    '/posts/NPUCTF2020-ezinclude': RouteRecordInfo<'/posts/NPUCTF2020-ezinclude', '/posts/NPUCTF2020-ezinclude', Record<never, never>, Record<never, never>>,
    '/posts/NPUCTF2020-ezlogin': RouteRecordInfo<'/posts/NPUCTF2020-ezlogin', '/posts/NPUCTF2020-ezlogin', Record<never, never>, Record<never, never>>,
    '/posts/NPUCTF2020-web🐕': RouteRecordInfo<'/posts/NPUCTF2020-web🐕', '/posts/NPUCTF2020-web🐕', Record<never, never>, Record<never, never>>,
    '/posts/NPUCTF2020-验证🐎': RouteRecordInfo<'/posts/NPUCTF2020-验证🐎', '/posts/NPUCTF2020-验证🐎', Record<never, never>, Record<never, never>>,
    '/posts/NSSRound': RouteRecordInfo<'/posts/NSSRound', '/posts/NSSRound', Record<never, never>, Record<never, never>>,
    '/posts/October-2019-Twice-SQL-Injection': RouteRecordInfo<'/posts/October-2019-Twice-SQL-Injection', '/posts/October-2019-Twice-SQL-Injection', Record<never, never>, Record<never, never>>,
    '/posts/PASECA2019-honey-shop': RouteRecordInfo<'/posts/PASECA2019-honey-shop', '/posts/PASECA2019-honey-shop', Record<never, never>, Record<never, never>>,
    '/posts/pasecactf-2019-flask-ssti': RouteRecordInfo<'/posts/pasecactf-2019-flask-ssti', '/posts/pasecactf-2019-flask-ssti', Record<never, never>, Record<never, never>>,
    '/posts/php': RouteRecordInfo<'/posts/php', '/posts/php', Record<never, never>, Record<never, never>>,
    '/posts/php特性': RouteRecordInfo<'/posts/php特性', '/posts/php特性', Record<never, never>, Record<never, never>>,
    '/posts/PWNHUB-公开赛-2018-傻-fufu-的工作日': RouteRecordInfo<'/posts/PWNHUB-公开赛-2018-傻-fufu-的工作日', '/posts/PWNHUB-公开赛-2018-傻-fufu-的工作日', Record<never, never>, Record<never, never>>,
    '/posts/PwnThyBytes-2019-Baby-SQL': RouteRecordInfo<'/posts/PwnThyBytes-2019-Baby-SQL', '/posts/PwnThyBytes-2019-Baby-SQL', Record<never, never>, Record<never, never>>,
    '/posts/PyCalX-1-2': RouteRecordInfo<'/posts/PyCalX-1-2', '/posts/PyCalX-1-2', Record<never, never>, Record<never, never>>,
    '/posts/python': RouteRecordInfo<'/posts/python', '/posts/python', Record<never, never>, Record<never, never>>,
    '/posts/QWB2021-Quals-托纳多': RouteRecordInfo<'/posts/QWB2021-Quals-托纳多', '/posts/QWB2021-Quals-托纳多', Record<never, never>, Record<never, never>>,
    '/posts/RCTF-2019-Nextphp': RouteRecordInfo<'/posts/RCTF-2019-Nextphp', '/posts/RCTF-2019-Nextphp', Record<never, never>, Record<never, never>>,
    '/posts/RCTF2015-EasySQL': RouteRecordInfo<'/posts/RCTF2015-EasySQL', '/posts/RCTF2015-EasySQL', Record<never, never>, Record<never, never>>,
    '/posts/RCTF2019-calcalcalc': RouteRecordInfo<'/posts/RCTF2019-calcalcalc', '/posts/RCTF2019-calcalcalc', Record<never, never>, Record<never, never>>,
    '/posts/re': RouteRecordInfo<'/posts/re', '/posts/re', Record<never, never>, Record<never, never>>,
    '/posts/RoarCTF-2019-Online-Proxy': RouteRecordInfo<'/posts/RoarCTF-2019-Online-Proxy', '/posts/RoarCTF-2019-Online-Proxy', Record<never, never>, Record<never, never>>,
    '/posts/RoarCTF-2019-Simple-Upload': RouteRecordInfo<'/posts/RoarCTF-2019-Simple-Upload', '/posts/RoarCTF-2019-Simple-Upload', Record<never, never>, Record<never, never>>,
    '/posts/RootersCTF2019-babyWeb': RouteRecordInfo<'/posts/RootersCTF2019-babyWeb', '/posts/RootersCTF2019-babyWeb', Record<never, never>, Record<never, never>>,
    '/posts/RootersCTF2019-I-3-Flask': RouteRecordInfo<'/posts/RootersCTF2019-I-3-Flask', '/posts/RootersCTF2019-I-3-Flask', Record<never, never>, Record<never, never>>,
    '/posts/RootersCTF2019-ImgXweb': RouteRecordInfo<'/posts/RootersCTF2019-ImgXweb', '/posts/RootersCTF2019-ImgXweb', Record<never, never>, Record<never, never>>,
    '/posts/rust学习': RouteRecordInfo<'/posts/rust学习', '/posts/rust学习', Record<never, never>, Record<never, never>>,
    '/posts/SageMath常用函数': RouteRecordInfo<'/posts/SageMath常用函数', '/posts/SageMath常用函数', Record<never, never>, Record<never, never>>,
    '/posts/SCTF2019-Flag-Shop': RouteRecordInfo<'/posts/SCTF2019-Flag-Shop', '/posts/SCTF2019-Flag-Shop', Record<never, never>, Record<never, never>>,
    '/posts/shCTF': RouteRecordInfo<'/posts/shCTF', '/posts/shCTF', Record<never, never>, Record<never, never>>,
    '/posts/sql注入总结': RouteRecordInfo<'/posts/sql注入总结', '/posts/sql注入总结', Record<never, never>, Record<never, never>>,
    '/posts/SUCTF-2018-annonymous': RouteRecordInfo<'/posts/SUCTF-2018-annonymous', '/posts/SUCTF-2018-annonymous', Record<never, never>, Record<never, never>>,
    '/posts/SUCTF-2018-GetShell': RouteRecordInfo<'/posts/SUCTF-2018-GetShell', '/posts/SUCTF-2018-GetShell', Record<never, never>, Record<never, never>>,
    '/posts/SUCTF-2018-MultiSQL': RouteRecordInfo<'/posts/SUCTF-2018-MultiSQL', '/posts/SUCTF-2018-MultiSQL', Record<never, never>, Record<never, never>>,
    '/posts/SUCTF-2019-EasyWeb': RouteRecordInfo<'/posts/SUCTF-2019-EasyWeb', '/posts/SUCTF-2019-EasyWeb', Record<never, never>, Record<never, never>>,
    '/posts/SUCTF-2019-Upload-Labs-2': RouteRecordInfo<'/posts/SUCTF-2019-Upload-Labs-2', '/posts/SUCTF-2019-Upload-Labs-2', Record<never, never>, Record<never, never>>,
    '/posts/SWPU2019-Web1': RouteRecordInfo<'/posts/SWPU2019-Web1', '/posts/SWPU2019-Web1', Record<never, never>, Record<never, never>>,
    '/posts/SWPU2019-Web3': RouteRecordInfo<'/posts/SWPU2019-Web3', '/posts/SWPU2019-Web3', Record<never, never>, Record<never, never>>,
    '/posts/SWPU2019-Web4': RouteRecordInfo<'/posts/SWPU2019-Web4', '/posts/SWPU2019-Web4', Record<never, never>, Record<never, never>>,
    '/posts/SWPUCTF-2016-Web7': RouteRecordInfo<'/posts/SWPUCTF-2016-Web7', '/posts/SWPUCTF-2016-Web7', Record<never, never>, Record<never, never>>,
    '/posts/SWPUCTF-2018-SimplePHP': RouteRecordInfo<'/posts/SWPUCTF-2018-SimplePHP', '/posts/SWPUCTF-2018-SimplePHP', Record<never, never>, Record<never, never>>,
    '/posts/upload': RouteRecordInfo<'/posts/upload', '/posts/upload', Record<never, never>, Record<never, never>>,
    '/posts/V-NCTF2025': RouteRecordInfo<'/posts/V-NCTF2025', '/posts/V-NCTF2025', Record<never, never>, Record<never, never>>,
    '/posts/virink-2019-files-share、': RouteRecordInfo<'/posts/virink-2019-files-share、', '/posts/virink-2019-files-share、', Record<never, never>, Record<never, never>>,
    '/posts/vulhub': RouteRecordInfo<'/posts/vulhub', '/posts/vulhub', Record<never, never>, Record<never, never>>,
    '/posts/Wallbreaker-Easy': RouteRecordInfo<'/posts/Wallbreaker-Easy', '/posts/Wallbreaker-Easy', Record<never, never>, Record<never, never>>,
    '/posts/watevrCTF-2019-Pickle-Store': RouteRecordInfo<'/posts/watevrCTF-2019-Pickle-Store', '/posts/watevrCTF-2019-Pickle-Store', Record<never, never>, Record<never, never>>,
    '/posts/watevrCTF-2019-Supercalc': RouteRecordInfo<'/posts/watevrCTF-2019-Supercalc', '/posts/watevrCTF-2019-Supercalc', Record<never, never>, Record<never, never>>,
    '/posts/WMCTF2020-Make-PHP-Great-Again': RouteRecordInfo<'/posts/WMCTF2020-Make-PHP-Great-Again', '/posts/WMCTF2020-Make-PHP-Great-Again', Record<never, never>, Record<never, never>>,
    '/posts/WMCTF2020-Make-PHP-Great-Again-2-0': RouteRecordInfo<'/posts/WMCTF2020-Make-PHP-Great-Again-2-0', '/posts/WMCTF2020-Make-PHP-Great-Again-2-0', Record<never, never>, Record<never, never>>,
    '/posts/WMCTF2020-Web-Check-in-2-0': RouteRecordInfo<'/posts/WMCTF2020-Web-Check-in-2-0', '/posts/WMCTF2020-Web-Check-in-2-0', Record<never, never>, Record<never, never>>,
    '/posts/WUSTCTF2020-CV-Maker': RouteRecordInfo<'/posts/WUSTCTF2020-CV-Maker', '/posts/WUSTCTF2020-CV-Maker', Record<never, never>, Record<never, never>>,
    '/posts/XDCTF-2015-filemanager': RouteRecordInfo<'/posts/XDCTF-2015-filemanager', '/posts/XDCTF-2015-filemanager', Record<never, never>, Record<never, never>>,
    '/posts/XNUCA2019Qualifier-EasyPHP': RouteRecordInfo<'/posts/XNUCA2019Qualifier-EasyPHP', '/posts/XNUCA2019Qualifier-EasyPHP', Record<never, never>, Record<never, never>>,
    '/posts/XYCTF2025': RouteRecordInfo<'/posts/XYCTF2025', '/posts/XYCTF2025', Record<never, never>, Record<never, never>>,
    '/posts/YLCTF': RouteRecordInfo<'/posts/YLCTF', '/posts/YLCTF', Record<never, never>, Record<never, never>>,
    '/posts/Zer0pts2020-Can-you-guess-it': RouteRecordInfo<'/posts/Zer0pts2020-Can-you-guess-it', '/posts/Zer0pts2020-Can-you-guess-it', Record<never, never>, Record<never, never>>,
    '/posts/Zer0pts2020-phpNantokaAdmin': RouteRecordInfo<'/posts/Zer0pts2020-phpNantokaAdmin', '/posts/Zer0pts2020-phpNantokaAdmin', Record<never, never>, Record<never, never>>,
    '/posts/博客是如何搭建的': RouteRecordInfo<'/posts/博客是如何搭建的', '/posts/博客是如何搭建的', Record<never, never>, Record<never, never>>,
    '/posts/反序列化': RouteRecordInfo<'/posts/反序列化', '/posts/反序列化', Record<never, never>, Record<never, never>>,
    '/posts/命令执行': RouteRecordInfo<'/posts/命令执行', '/posts/命令执行', Record<never, never>, Record<never, never>>,
    '/posts/安洵杯-2019-iamthinking': RouteRecordInfo<'/posts/安洵杯-2019-iamthinking', '/posts/安洵杯-2019-iamthinking', Record<never, never>, Record<never, never>>,
    '/posts/安洵杯-2019-不是文件上传': RouteRecordInfo<'/posts/安洵杯-2019-不是文件上传', '/posts/安洵杯-2019-不是文件上传', Record<never, never>, Record<never, never>>,
    '/posts/密码图形': RouteRecordInfo<'/posts/密码图形', '/posts/密码图形', Record<never, never>, Record<never, never>>,
    '/posts/强网杯-2019-Upload': RouteRecordInfo<'/posts/强网杯-2019-Upload', '/posts/强网杯-2019-Upload', Record<never, never>, Record<never, never>>,
    '/posts/御宛杯2024': RouteRecordInfo<'/posts/御宛杯2024', '/posts/御宛杯2024', Record<never, never>, Record<never, never>>,
    '/posts/文件幻术头': RouteRecordInfo<'/posts/文件幻术头', '/posts/文件幻术头', Record<never, never>, Record<never, never>>,
    '/posts/极客大挑战-2020-Greatphp': RouteRecordInfo<'/posts/极客大挑战-2020-Greatphp', '/posts/极客大挑战-2020-Greatphp', Record<never, never>, Record<never, never>>,
    '/posts/极客大挑战-2020-Roamphp1-Welcome': RouteRecordInfo<'/posts/极客大挑战-2020-Roamphp1-Welcome', '/posts/极客大挑战-2020-Roamphp1-Welcome', Record<never, never>, Record<never, never>>,
    '/posts/极客大挑战-2020-Roamphp2-Myblog': RouteRecordInfo<'/posts/极客大挑战-2020-Roamphp2-Myblog', '/posts/极客大挑战-2020-Roamphp2-Myblog', Record<never, never>, Record<never, never>>,
    '/posts/极客大挑战-2020-Roamphp4-Rceme': RouteRecordInfo<'/posts/极客大挑战-2020-Roamphp4-Rceme', '/posts/极客大挑战-2020-Roamphp4-Rceme', Record<never, never>, Record<never, never>>,
    '/posts/正则表达式语法': RouteRecordInfo<'/posts/正则表达式语法', '/posts/正则表达式语法', Record<never, never>, Record<never, never>>,
    '/posts/武功论剑': RouteRecordInfo<'/posts/武功论剑', '/posts/武功论剑', Record<never, never>, Record<never, never>>,
    '/posts/简单的登录界面': RouteRecordInfo<'/posts/简单的登录界面', '/posts/简单的登录界面', Record<never, never>, Record<never, never>>,
    '/posts/红明谷CTF-2021-EasyTP': RouteRecordInfo<'/posts/红明谷CTF-2021-EasyTP', '/posts/红明谷CTF-2021-EasyTP', Record<never, never>, Record<never, never>>,
    '/posts/红明谷CTF-2021-JavaWeb': RouteRecordInfo<'/posts/红明谷CTF-2021-JavaWeb', '/posts/红明谷CTF-2021-JavaWeb', Record<never, never>, Record<never, never>>,
    '/posts/红明谷CTF-2021-write-shell': RouteRecordInfo<'/posts/红明谷CTF-2021-write-shell', '/posts/红明谷CTF-2021-write-shell', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2018-Comment': RouteRecordInfo<'/posts/网鼎杯-2018-Comment', '/posts/网鼎杯-2018-Comment', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2020-半决赛-AliceWebsite': RouteRecordInfo<'/posts/网鼎杯-2020-半决赛-AliceWebsite', '/posts/网鼎杯-2020-半决赛-AliceWebsite', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2020-半决赛-BabyJS': RouteRecordInfo<'/posts/网鼎杯-2020-半决赛-BabyJS', '/posts/网鼎杯-2020-半决赛-BabyJS', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2020-半决赛-faka': RouteRecordInfo<'/posts/网鼎杯-2020-半决赛-faka', '/posts/网鼎杯-2020-半决赛-faka', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2020-玄武组-SSRFMe': RouteRecordInfo<'/posts/网鼎杯-2020-玄武组-SSRFMe', '/posts/网鼎杯-2020-玄武组-SSRFMe', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2020-白虎组-PicDown': RouteRecordInfo<'/posts/网鼎杯-2020-白虎组-PicDown', '/posts/网鼎杯-2020-白虎组-PicDown', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯-2020-青龙组-notes': RouteRecordInfo<'/posts/网鼎杯-2020-青龙组-notes', '/posts/网鼎杯-2020-青龙组-notes', Record<never, never>, Record<never, never>>,
    '/posts/网鼎杯2018-Unfinish': RouteRecordInfo<'/posts/网鼎杯2018-Unfinish', '/posts/网鼎杯2018-Unfinish', Record<never, never>, Record<never, never>>,
    '/posts/羊城杯-2020-Blackcat、': RouteRecordInfo<'/posts/羊城杯-2020-Blackcat、', '/posts/羊城杯-2020-Blackcat、', Record<never, never>, Record<never, never>>,
    '/posts/羊城杯-2020-Easyphp2': RouteRecordInfo<'/posts/羊城杯-2020-Easyphp2', '/posts/羊城杯-2020-Easyphp2', Record<never, never>, Record<never, never>>,
    '/posts/羊城杯-2020-EasySer': RouteRecordInfo<'/posts/羊城杯-2020-EasySer', '/posts/羊城杯-2020-EasySer', Record<never, never>, Record<never, never>>,
    '/posts/羊城杯2020-easyphp': RouteRecordInfo<'/posts/羊城杯2020-easyphp', '/posts/羊城杯2020-easyphp', Record<never, never>, Record<never, never>>,
    '/posts/蓝帽杯-2021-One-Pointer-PHP': RouteRecordInfo<'/posts/蓝帽杯-2021-One-Pointer-PHP', '/posts/蓝帽杯-2021-One-Pointer-PHP', Record<never, never>, Record<never, never>>,
    '/posts/解密网站': RouteRecordInfo<'/posts/解密网站', '/posts/解密网站', Record<never, never>, Record<never, never>>,
    '/posts/高明的黑客': RouteRecordInfo<'/posts/高明的黑客', '/posts/高明的黑客', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.2_vue@3.5.18_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes: '/'
      views: never
    }
    'node_modules/.pnpm/valaxy@0.26.2_@babel+parser_dba4d91b61cfe38809aac9d109be796b/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.2_vue@3.5.18_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes: '/page/[page]'
      views: never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.2_vue@3.5.18_typescript@5.9.2_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/0CTF-2016-piapiapia.md': {
      routes: '/posts/0CTF-2016-piapiapia'
      views: never
    }
    'pages/posts/2020-新春红包题-1.md': {
      routes: '/posts/2020-新春红包题-1'
      views: never
    }
    'pages/posts/2021祥云杯-Package-Manager-2021.md': {
      routes: '/posts/2021祥云杯-Package-Manager-2021'
      views: never
    }
    'pages/posts/2021祥云杯-secrets-of-admin.md': {
      routes: '/posts/2021祥云杯-secrets-of-admin'
      views: never
    }
    'pages/posts/2024-NSS秋季赛.md': {
      routes: '/posts/2024-NSS秋季赛'
      views: never
    }
    'pages/posts/2024国城杯部分wp.md': {
      routes: '/posts/2024国城杯部分wp'
      views: never
    }
    'pages/posts/aliyunctf2025.md': {
      routes: '/posts/aliyunctf2025'
      views: never
    }
    'pages/posts/b01lers2020-Life-on-Mars.md': {
      routes: '/posts/b01lers2020-Life-on-Mars'
      views: never
    }
    'pages/posts/b01lers2020-Scrambled.md': {
      routes: '/posts/b01lers2020-Scrambled'
      views: never
    }
    'pages/posts/b01lers2020-Welcome-to-Earth.md': {
      routes: '/posts/b01lers2020-Welcome-to-Earth'
      views: never
    }
    'pages/posts/Basectf.md': {
      routes: '/posts/Basectf'
      views: never
    }
    'pages/posts/bestphp-s-revenge.md': {
      routes: '/posts/bestphp-s-revenge'
      views: never
    }
    'pages/posts/BJDCTF2020-EzPHP.md': {
      routes: '/posts/BJDCTF2020-EzPHP'
      views: never
    }
    'pages/posts/Black-Watch-入群题-Web.md': {
      routes: '/posts/Black-Watch-入群题-Web'
      views: never
    }
    'pages/posts/blog奇葩问题组合.md': {
      routes: '/posts/blog奇葩问题组合'
      views: never
    }
    'pages/posts/BSidesCF-2019-Mixer.md': {
      routes: '/posts/BSidesCF-2019-Mixer'
      views: never
    }
    'pages/posts/BSidesCF-2019-Pick-Tac-Toe.md': {
      routes: '/posts/BSidesCF-2019-Pick-Tac-Toe'
      views: never
    }
    'pages/posts/BSidesCF-2019-Sequel.md': {
      routes: '/posts/BSidesCF-2019-Sequel'
      views: never
    }
    'pages/posts/BSidesCF-2019-SVGMagic.md': {
      routes: '/posts/BSidesCF-2019-SVGMagic'
      views: never
    }
    'pages/posts/BSidesCF-2020-Cards.md': {
      routes: '/posts/BSidesCF-2020-Cards'
      views: never
    }
    'pages/posts/BSidesCF-2020-Hurdles.md': {
      routes: '/posts/BSidesCF-2020-Hurdles'
      views: never
    }
    'pages/posts/BuildCTF.md': {
      routes: '/posts/BuildCTF'
      views: never
    }
    'pages/posts/CISCN2019-华东北赛区-Web2.md': {
      routes: '/posts/CISCN2019-华东北赛区-Web2'
      views: never
    }
    'pages/posts/CISCN2019-华东南赛区-Double-Secret.md': {
      routes: '/posts/CISCN2019-华东南赛区-Double-Secret'
      views: never
    }
    'pages/posts/CISCN2019-华东南赛区-Web4.md': {
      routes: '/posts/CISCN2019-华东南赛区-Web4'
      views: never
    }
    'pages/posts/CISCN2019-华北赛区-Day1-Web1-Dropbox.md': {
      routes: '/posts/CISCN2019-华北赛区-Day1-Web1-Dropbox'
      views: never
    }
    'pages/posts/CISCN2019-华北赛区-Day1-Web2-ikun.md': {
      routes: '/posts/CISCN2019-华北赛区-Day1-Web2-ikun'
      views: never
    }
    'pages/posts/CISCN2019-华北赛区-Day1-Web5-CyberPunk.md': {
      routes: '/posts/CISCN2019-华北赛区-Day1-Web5-CyberPunk'
      views: never
    }
    'pages/posts/CISCN2019-总决赛-Day1-Web4-Laravel1.md': {
      routes: '/posts/CISCN2019-总决赛-Day1-Web4-Laravel1'
      views: never
    }
    'pages/posts/CISCN2019-总决赛-Day2-Web1-Easyweb.md': {
      routes: '/posts/CISCN2019-总决赛-Day2-Web1-Easyweb'
      views: never
    }
    'pages/posts/CISCN2021-Quals-upload.md': {
      routes: '/posts/CISCN2021-Quals-upload'
      views: never
    }
    'pages/posts/crypto.md': {
      routes: '/posts/crypto'
      views: never
    }
    'pages/posts/crypto-1.md': {
      routes: '/posts/crypto-1'
      views: never
    }
    'pages/posts/crypto-AES-DES.md': {
      routes: '/posts/crypto-AES-DES'
      views: never
    }
    'pages/posts/crypto-ECC加密.md': {
      routes: '/posts/crypto-ECC加密'
      views: never
    }
    'pages/posts/crypto-rsa.md': {
      routes: '/posts/crypto-rsa'
      views: never
    }
    'pages/posts/crypto-suanfa.md': {
      routes: '/posts/crypto-suanfa'
      views: never
    }
    'pages/posts/CSAWQual-2016-i-got-id.md': {
      routes: '/posts/CSAWQual-2016-i-got-id'
      views: never
    }
    'pages/posts/CSAWQual-2019-Web-Unagi.md': {
      routes: '/posts/CSAWQual-2019-Web-Unagi'
      views: never
    }
    'pages/posts/CSCCTF-2019-Qual-FlaskLight.md': {
      routes: '/posts/CSCCTF-2019-Qual-FlaskLight'
      views: never
    }
    'pages/posts/ctfshow-java.md': {
      routes: '/posts/ctfshow-java'
      views: never
    }
    'pages/posts/ctfshow-php特性.md': {
      routes: '/posts/ctfshow-php特性'
      views: never
    }
    'pages/posts/ctfshow-ssrf.md': {
      routes: '/posts/ctfshow-ssrf'
      views: never
    }
    'pages/posts/ctfshow-ssti.md': {
      routes: '/posts/ctfshow-ssti'
      views: never
    }
    'pages/posts/ctfshow-xss.md': {
      routes: '/posts/ctfshow-xss'
      views: never
    }
    'pages/posts/ctfshow-xxe.md': {
      routes: '/posts/ctfshow-xxe'
      views: never
    }
    'pages/posts/ctfshow-信息搜集.md': {
      routes: '/posts/ctfshow-信息搜集'
      views: never
    }
    'pages/posts/ctfshow-命令执行.md': {
      routes: '/posts/ctfshow-命令执行'
      views: never
    }
    'pages/posts/ctfshow-常用姿势.md': {
      routes: '/posts/ctfshow-常用姿势'
      views: never
    }
    'pages/posts/ctfshow-文件上传.md': {
      routes: '/posts/ctfshow-文件上传'
      views: never
    }
    'pages/posts/ctfshow文件包含.md': {
      routes: '/posts/ctfshow文件包含'
      views: never
    }
    'pages/posts/DDCTF-2019-homebrew-event-loop.md': {
      routes: '/posts/DDCTF-2019-homebrew-event-loop'
      views: never
    }
    'pages/posts/De1CTF-2019-Giftbox.md': {
      routes: '/posts/De1CTF-2019-Giftbox'
      views: never
    }
    'pages/posts/De1CTF-2019-ShellShellShell.md': {
      routes: '/posts/De1CTF-2019-ShellShellShell'
      views: never
    }
    'pages/posts/Dest0g3-520迎新赛-EasySSTI.md': {
      routes: '/posts/Dest0g3-520迎新赛-EasySSTI'
      views: never
    }
    'pages/posts/Dest0g3-520迎新赛-SimpleRCE.md': {
      routes: '/posts/Dest0g3-520迎新赛-SimpleRCE'
      views: never
    }
    'pages/posts/EasyBypass.md': {
      routes: '/posts/EasyBypass'
      views: never
    }
    'pages/posts/EIS-2019-EzPOP.md': {
      routes: '/posts/EIS-2019-EzPOP'
      views: never
    }
    'pages/posts/FBCTF2019-Event.md': {
      routes: '/posts/FBCTF2019-Event'
      views: never
    }
    'pages/posts/FBCTF2019-Products-Manager.md': {
      routes: '/posts/FBCTF2019-Products-Manager'
      views: never
    }
    'pages/posts/FBCTF2019-RCEService.md': {
      routes: '/posts/FBCTF2019-RCEService'
      views: never
    }
    'pages/posts/FireshellCTF2020-Caas.md': {
      routes: '/posts/FireshellCTF2020-Caas'
      views: never
    }
    'pages/posts/FireshellCTF2020-ScreenShooter.md': {
      routes: '/posts/FireshellCTF2020-ScreenShooter'
      views: never
    }
    'pages/posts/FireshellCTF2020-URL-TO-PDF.md': {
      routes: '/posts/FireshellCTF2020-URL-TO-PDF'
      views: never
    }
    'pages/posts/GHCTF2025.md': {
      routes: '/posts/GHCTF2025'
      views: never
    }
    'pages/posts/GKCTF-2021-babycat-revenge.md': {
      routes: '/posts/GKCTF-2021-babycat-revenge'
      views: never
    }
    'pages/posts/GKCTF-2021-CheckBot.md': {
      routes: '/posts/GKCTF-2021-CheckBot'
      views: never
    }
    'pages/posts/GKCTF-2021-easycms.md': {
      routes: '/posts/GKCTF-2021-easycms'
      views: never
    }
    'pages/posts/GKCTF2020-cve版签到.md': {
      routes: '/posts/GKCTF2020-cve版签到'
      views: never
    }
    'pages/posts/GoogleCTF2019-Quals-Bnv.md': {
      routes: '/posts/GoogleCTF2019-Quals-Bnv'
      views: never
    }
    'pages/posts/GWCTF-2019-mypassword.md': {
      routes: '/posts/GWCTF-2019-mypassword'
      views: never
    }
    'pages/posts/GWCTF-2019-你的名字.md': {
      routes: '/posts/GWCTF-2019-你的名字'
      views: never
    }
    'pages/posts/GWCTF-2019-枯燥的抽奖.md': {
      routes: '/posts/GWCTF-2019-枯燥的抽奖'
      views: never
    }
    'pages/posts/GXYCTF2019-BabysqliV3-0.md': {
      routes: '/posts/GXYCTF2019-BabysqliV3-0'
      views: never
    }
    'pages/posts/GXYCTF2019-StrongestMind.md': {
      routes: '/posts/GXYCTF2019-StrongestMind'
      views: never
    }
    'pages/posts/GYCTF2020-Easyphp.md': {
      routes: '/posts/GYCTF2020-Easyphp'
      views: never
    }
    'pages/posts/GYCTF2020-EasyThinking.md': {
      routes: '/posts/GYCTF2020-EasyThinking'
      views: never
    }
    'pages/posts/GYCTF2020-Ez-Express.md': {
      routes: '/posts/GYCTF2020-Ez-Express'
      views: never
    }
    'pages/posts/GYCTF2020-Ezsqli.md': {
      routes: '/posts/GYCTF2020-Ezsqli'
      views: never
    }
    'pages/posts/GYCTF2020-FlaskApp.md': {
      routes: '/posts/GYCTF2020-FlaskApp'
      views: never
    }
    'pages/posts/GYCTF2020-Node-Game-1.md': {
      routes: '/posts/GYCTF2020-Node-Game-1'
      views: never
    }
    'pages/posts/HarekazeCTF2019-Avatar-Uploader-1.md': {
      routes: '/posts/HarekazeCTF2019-Avatar-Uploader-1'
      views: never
    }
    'pages/posts/HarekazeCTF2019-Easy-Notes.md': {
      routes: '/posts/HarekazeCTF2019-Easy-Notes'
      views: never
    }
    'pages/posts/HarekazeCTF2019-encode-and-encode.md': {
      routes: '/posts/HarekazeCTF2019-encode-and-encode'
      views: never
    }
    'pages/posts/HarekazeCTF2019-Sqlite-Voting.md': {
      routes: '/posts/HarekazeCTF2019-Sqlite-Voting'
      views: never
    }
    'pages/posts/HCTF-2018-Hideandseek.md': {
      routes: '/posts/HCTF-2018-Hideandseek'
      views: never
    }
    'pages/posts/hello-valaxy.md': {
      routes: '/posts/hello-valaxy'
      views: never
    }
    'pages/posts/hello-world.md': {
      routes: '/posts/hello-world'
      views: never
    }
    'pages/posts/HFCTF-2021-Final-easyflask.md': {
      routes: '/posts/HFCTF-2021-Final-easyflask'
      views: never
    }
    'pages/posts/HFCTF-2021-Final-hatenum.md': {
      routes: '/posts/HFCTF-2021-Final-hatenum'
      views: never
    }
    'pages/posts/HFCTF2020-BabyUpload.md': {
      routes: '/posts/HFCTF2020-BabyUpload'
      views: never
    }
    'pages/posts/HFCTF2020-EasyLogin.md': {
      routes: '/posts/HFCTF2020-EasyLogin'
      views: never
    }
    'pages/posts/HFCTF2020-JustEscape.md': {
      routes: '/posts/HFCTF2020-JustEscape'
      views: never
    }
    'pages/posts/HFCTF2021-Quals-Unsetme.md': {
      routes: '/posts/HFCTF2021-Quals-Unsetme'
      views: never
    }
    'pages/posts/HITCON-2016-Leaking.md': {
      routes: '/posts/HITCON-2016-Leaking'
      views: never
    }
    'pages/posts/HITCON-2017-SSRFme.md': {
      routes: '/posts/HITCON-2017-SSRFme'
      views: never
    }
    'pages/posts/HMGCTF2022-Fan-Website.md': {
      routes: '/posts/HMGCTF2022-Fan-Website'
      views: never
    }
    'pages/posts/HMGCTF2022-Smarty-Calculator.md': {
      routes: '/posts/HMGCTF2022-Smarty-Calculator'
      views: never
    }
    'pages/posts/HNCTF-2022-WEEK2-ez-ssrf.md': {
      routes: '/posts/HNCTF-2022-WEEK2-ez-ssrf'
      views: never
    }
    'pages/posts/HNCTF-2022-WEEK4-unf1ni3hed-web3he1.md': {
      routes: '/posts/HNCTF-2022-WEEK4-unf1ni3hed-web3he1'
      views: never
    }
    'pages/posts/HTML学习篇.md': {
      routes: '/posts/HTML学习篇'
      views: never
    }
    'pages/posts/HXBCTF-2021-easywill.md': {
      routes: '/posts/HXBCTF-2021-easywill'
      views: never
    }
    'pages/posts/isctf2024 web.md': {
      routes: '/posts/isctf2024 web'
      views: never
    }
    'pages/posts/isctf2024-crypto.md': {
      routes: '/posts/isctf2024-crypto'
      views: never
    }
    'pages/posts/ISITDTU-2019-EasyPHP.md': {
      routes: '/posts/ISITDTU-2019-EasyPHP'
      views: never
    }
    'pages/posts/Java.md': {
      routes: '/posts/Java'
      views: never
    }
    'pages/posts/java-sec-code.md': {
      routes: '/posts/java-sec-code'
      views: never
    }
    'pages/posts/Javaweb.md': {
      routes: '/posts/Javaweb'
      views: never
    }
    'pages/posts/java反序列化.md': {
      routes: '/posts/java反序列化'
      views: never
    }
    'pages/posts/JMCTF-2021-GoOSS.md': {
      routes: '/posts/JMCTF-2021-GoOSS'
      views: never
    }
    'pages/posts/JMCTF-2021-UploadHub.md': {
      routes: '/posts/JMCTF-2021-UploadHub'
      views: never
    }
    'pages/posts/LineCTF2022-BB.md': {
      routes: '/posts/LineCTF2022-BB'
      views: never
    }
    'pages/posts/LineCTF2022-gotm.md': {
      routes: '/posts/LineCTF2022-gotm'
      views: never
    }
    'pages/posts/md5.md': {
      routes: '/posts/md5'
      views: never
    }
    'pages/posts/misc.md': {
      routes: '/posts/misc'
      views: never
    }
    'pages/posts/MoeCTF.md': {
      routes: '/posts/MoeCTF'
      views: never
    }
    'pages/posts/MoeCTF-2025.md': {
      routes: '/posts/MoeCTF-2025'
      views: never
    }
    'pages/posts/MRCTF2020-Ezaudit.md': {
      routes: '/posts/MRCTF2020-Ezaudit'
      views: never
    }
    'pages/posts/MRCTF2020-Ezpop-Revenge.md': {
      routes: '/posts/MRCTF2020-Ezpop-Revenge'
      views: never
    }
    'pages/posts/MRCTF2020套娃.md': {
      routes: '/posts/MRCTF2020套娃'
      views: never
    }
    'pages/posts/MySQL学习.md': {
      routes: '/posts/MySQL学习'
      views: never
    }
    'pages/posts/N1CTF-2018-eating-cms.md': {
      routes: '/posts/N1CTF-2018-eating-cms'
      views: never
    }
    'pages/posts/NCTF-2024.md': {
      routes: '/posts/NCTF-2024'
      views: never
    }
    'pages/posts/NCTF2019-SQLi.md': {
      routes: '/posts/NCTF2019-SQLi'
      views: never
    }
    'pages/posts/NCTF2019-True-XML-cookbook.md': {
      routes: '/posts/NCTF2019-True-XML-cookbook'
      views: never
    }
    'pages/posts/NESTCTF-2019-Love-Math-2.md': {
      routes: '/posts/NESTCTF-2019-Love-Math-2'
      views: never
    }
    'pages/posts/new-star-CTF.md': {
      routes: '/posts/new-star-CTF'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-Begin-of-HTTP.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-Begin-of-HTTP'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-EasyLogin.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-EasyLogin'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-ez-sql.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-ez-sql'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-Include-🍐.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-Include-🍐'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-include-0。0.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-include-0。0'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-midsql.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-midsql'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-POP-Gadget.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-POP-Gadget'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-R-C-E.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-R-C-E'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-泄漏的秘密.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-泄漏的秘密'
      views: never
    }
    'pages/posts/NewStarCTF-2023-公开赛道-逃.md': {
      routes: '/posts/NewStarCTF-2023-公开赛道-逃'
      views: never
    }
    'pages/posts/NewStarCTF-公开赛赛道-BabySSTI-Three.md': {
      routes: '/posts/NewStarCTF-公开赛赛道-BabySSTI-Three'
      views: never
    }
    'pages/posts/NewStarCTF-公开赛赛道-BabySSTI-Two.md': {
      routes: '/posts/NewStarCTF-公开赛赛道-BabySSTI-Two'
      views: never
    }
    'pages/posts/NewStarCTF-公开赛赛道-So-Baby-RCE.md': {
      routes: '/posts/NewStarCTF-公开赛赛道-So-Baby-RCE'
      views: never
    }
    'pages/posts/NewStarCTF-公开赛赛道-So-Baby-RCE-Again.md': {
      routes: '/posts/NewStarCTF-公开赛赛道-So-Baby-RCE-Again'
      views: never
    }
    'pages/posts/NewStarCTF-公开赛赛道-UnserializeOne.md': {
      routes: '/posts/NewStarCTF-公开赛赛道-UnserializeOne'
      views: never
    }
    'pages/posts/NPUCTF2020-ezinclude.md': {
      routes: '/posts/NPUCTF2020-ezinclude'
      views: never
    }
    'pages/posts/NPUCTF2020-ezlogin.md': {
      routes: '/posts/NPUCTF2020-ezlogin'
      views: never
    }
    'pages/posts/NPUCTF2020-web🐕.md': {
      routes: '/posts/NPUCTF2020-web🐕'
      views: never
    }
    'pages/posts/NPUCTF2020-验证🐎.md': {
      routes: '/posts/NPUCTF2020-验证🐎'
      views: never
    }
    'pages/posts/NSSRound.md': {
      routes: '/posts/NSSRound'
      views: never
    }
    'pages/posts/October-2019-Twice-SQL-Injection.md': {
      routes: '/posts/October-2019-Twice-SQL-Injection'
      views: never
    }
    'pages/posts/PASECA2019-honey-shop.md': {
      routes: '/posts/PASECA2019-honey-shop'
      views: never
    }
    'pages/posts/pasecactf-2019-flask-ssti.md': {
      routes: '/posts/pasecactf-2019-flask-ssti'
      views: never
    }
    'pages/posts/php.md': {
      routes: '/posts/php'
      views: never
    }
    'pages/posts/php特性.md': {
      routes: '/posts/php特性'
      views: never
    }
    'pages/posts/PWNHUB-公开赛-2018-傻-fufu-的工作日.md': {
      routes: '/posts/PWNHUB-公开赛-2018-傻-fufu-的工作日'
      views: never
    }
    'pages/posts/PwnThyBytes-2019-Baby-SQL.md': {
      routes: '/posts/PwnThyBytes-2019-Baby-SQL'
      views: never
    }
    'pages/posts/PyCalX-1-2.md': {
      routes: '/posts/PyCalX-1-2'
      views: never
    }
    'pages/posts/python.md': {
      routes: '/posts/python'
      views: never
    }
    'pages/posts/QWB2021-Quals-托纳多.md': {
      routes: '/posts/QWB2021-Quals-托纳多'
      views: never
    }
    'pages/posts/RCTF-2019-Nextphp.md': {
      routes: '/posts/RCTF-2019-Nextphp'
      views: never
    }
    'pages/posts/RCTF2015-EasySQL.md': {
      routes: '/posts/RCTF2015-EasySQL'
      views: never
    }
    'pages/posts/RCTF2019-calcalcalc.md': {
      routes: '/posts/RCTF2019-calcalcalc'
      views: never
    }
    'pages/posts/re.md': {
      routes: '/posts/re'
      views: never
    }
    'pages/posts/RoarCTF-2019-Online-Proxy.md': {
      routes: '/posts/RoarCTF-2019-Online-Proxy'
      views: never
    }
    'pages/posts/RoarCTF-2019-Simple-Upload.md': {
      routes: '/posts/RoarCTF-2019-Simple-Upload'
      views: never
    }
    'pages/posts/RootersCTF2019-babyWeb.md': {
      routes: '/posts/RootersCTF2019-babyWeb'
      views: never
    }
    'pages/posts/RootersCTF2019-I-3-Flask.md': {
      routes: '/posts/RootersCTF2019-I-3-Flask'
      views: never
    }
    'pages/posts/RootersCTF2019-ImgXweb.md': {
      routes: '/posts/RootersCTF2019-ImgXweb'
      views: never
    }
    'pages/posts/rust学习.md': {
      routes: '/posts/rust学习'
      views: never
    }
    'pages/posts/SageMath常用函数.md': {
      routes: '/posts/SageMath常用函数'
      views: never
    }
    'pages/posts/SCTF2019-Flag-Shop.md': {
      routes: '/posts/SCTF2019-Flag-Shop'
      views: never
    }
    'pages/posts/shCTF.md': {
      routes: '/posts/shCTF'
      views: never
    }
    'pages/posts/sql注入总结.md': {
      routes: '/posts/sql注入总结'
      views: never
    }
    'pages/posts/SUCTF-2018-annonymous.md': {
      routes: '/posts/SUCTF-2018-annonymous'
      views: never
    }
    'pages/posts/SUCTF-2018-GetShell.md': {
      routes: '/posts/SUCTF-2018-GetShell'
      views: never
    }
    'pages/posts/SUCTF-2018-MultiSQL.md': {
      routes: '/posts/SUCTF-2018-MultiSQL'
      views: never
    }
    'pages/posts/SUCTF-2019-EasyWeb.md': {
      routes: '/posts/SUCTF-2019-EasyWeb'
      views: never
    }
    'pages/posts/SUCTF-2019-Upload-Labs-2.md': {
      routes: '/posts/SUCTF-2019-Upload-Labs-2'
      views: never
    }
    'pages/posts/SWPU2019-Web1.md': {
      routes: '/posts/SWPU2019-Web1'
      views: never
    }
    'pages/posts/SWPU2019-Web3.md': {
      routes: '/posts/SWPU2019-Web3'
      views: never
    }
    'pages/posts/SWPU2019-Web4.md': {
      routes: '/posts/SWPU2019-Web4'
      views: never
    }
    'pages/posts/SWPUCTF-2016-Web7.md': {
      routes: '/posts/SWPUCTF-2016-Web7'
      views: never
    }
    'pages/posts/SWPUCTF-2018-SimplePHP.md': {
      routes: '/posts/SWPUCTF-2018-SimplePHP'
      views: never
    }
    'pages/posts/upload.md': {
      routes: '/posts/upload'
      views: never
    }
    'pages/posts/V-NCTF2025.md': {
      routes: '/posts/V-NCTF2025'
      views: never
    }
    'pages/posts/virink-2019-files-share、.md': {
      routes: '/posts/virink-2019-files-share、'
      views: never
    }
    'pages/posts/vulhub.md': {
      routes: '/posts/vulhub'
      views: never
    }
    'pages/posts/Wallbreaker-Easy.md': {
      routes: '/posts/Wallbreaker-Easy'
      views: never
    }
    'pages/posts/watevrCTF-2019-Pickle-Store.md': {
      routes: '/posts/watevrCTF-2019-Pickle-Store'
      views: never
    }
    'pages/posts/watevrCTF-2019-Supercalc.md': {
      routes: '/posts/watevrCTF-2019-Supercalc'
      views: never
    }
    'pages/posts/WMCTF2020-Make-PHP-Great-Again.md': {
      routes: '/posts/WMCTF2020-Make-PHP-Great-Again'
      views: never
    }
    'pages/posts/WMCTF2020-Make-PHP-Great-Again-2-0.md': {
      routes: '/posts/WMCTF2020-Make-PHP-Great-Again-2-0'
      views: never
    }
    'pages/posts/WMCTF2020-Web-Check-in-2-0.md': {
      routes: '/posts/WMCTF2020-Web-Check-in-2-0'
      views: never
    }
    'pages/posts/WUSTCTF2020-CV-Maker.md': {
      routes: '/posts/WUSTCTF2020-CV-Maker'
      views: never
    }
    'pages/posts/XDCTF-2015-filemanager.md': {
      routes: '/posts/XDCTF-2015-filemanager'
      views: never
    }
    'pages/posts/XNUCA2019Qualifier-EasyPHP.md': {
      routes: '/posts/XNUCA2019Qualifier-EasyPHP'
      views: never
    }
    'pages/posts/XYCTF2025.md': {
      routes: '/posts/XYCTF2025'
      views: never
    }
    'pages/posts/YLCTF.md': {
      routes: '/posts/YLCTF'
      views: never
    }
    'pages/posts/Zer0pts2020-Can-you-guess-it.md': {
      routes: '/posts/Zer0pts2020-Can-you-guess-it'
      views: never
    }
    'pages/posts/Zer0pts2020-phpNantokaAdmin.md': {
      routes: '/posts/Zer0pts2020-phpNantokaAdmin'
      views: never
    }
    'pages/posts/博客是如何搭建的.md': {
      routes: '/posts/博客是如何搭建的'
      views: never
    }
    'pages/posts/反序列化.md': {
      routes: '/posts/反序列化'
      views: never
    }
    'pages/posts/命令执行.md': {
      routes: '/posts/命令执行'
      views: never
    }
    'pages/posts/安洵杯-2019-iamthinking.md': {
      routes: '/posts/安洵杯-2019-iamthinking'
      views: never
    }
    'pages/posts/安洵杯-2019-不是文件上传.md': {
      routes: '/posts/安洵杯-2019-不是文件上传'
      views: never
    }
    'pages/posts/密码图形.md': {
      routes: '/posts/密码图形'
      views: never
    }
    'pages/posts/强网杯-2019-Upload.md': {
      routes: '/posts/强网杯-2019-Upload'
      views: never
    }
    'pages/posts/御宛杯2024.md': {
      routes: '/posts/御宛杯2024'
      views: never
    }
    'pages/posts/文件幻术头.md': {
      routes: '/posts/文件幻术头'
      views: never
    }
    'pages/posts/极客大挑战-2020-Greatphp.md': {
      routes: '/posts/极客大挑战-2020-Greatphp'
      views: never
    }
    'pages/posts/极客大挑战-2020-Roamphp1-Welcome.md': {
      routes: '/posts/极客大挑战-2020-Roamphp1-Welcome'
      views: never
    }
    'pages/posts/极客大挑战-2020-Roamphp2-Myblog.md': {
      routes: '/posts/极客大挑战-2020-Roamphp2-Myblog'
      views: never
    }
    'pages/posts/极客大挑战-2020-Roamphp4-Rceme.md': {
      routes: '/posts/极客大挑战-2020-Roamphp4-Rceme'
      views: never
    }
    'pages/posts/正则表达式语法.md': {
      routes: '/posts/正则表达式语法'
      views: never
    }
    'pages/posts/武功论剑.md': {
      routes: '/posts/武功论剑'
      views: never
    }
    'pages/posts/简单的登录界面.md': {
      routes: '/posts/简单的登录界面'
      views: never
    }
    'pages/posts/红明谷CTF-2021-EasyTP.md': {
      routes: '/posts/红明谷CTF-2021-EasyTP'
      views: never
    }
    'pages/posts/红明谷CTF-2021-JavaWeb.md': {
      routes: '/posts/红明谷CTF-2021-JavaWeb'
      views: never
    }
    'pages/posts/红明谷CTF-2021-write-shell.md': {
      routes: '/posts/红明谷CTF-2021-write-shell'
      views: never
    }
    'pages/posts/网鼎杯-2018-Comment.md': {
      routes: '/posts/网鼎杯-2018-Comment'
      views: never
    }
    'pages/posts/网鼎杯-2020-半决赛-AliceWebsite.md': {
      routes: '/posts/网鼎杯-2020-半决赛-AliceWebsite'
      views: never
    }
    'pages/posts/网鼎杯-2020-半决赛-BabyJS.md': {
      routes: '/posts/网鼎杯-2020-半决赛-BabyJS'
      views: never
    }
    'pages/posts/网鼎杯-2020-半决赛-faka.md': {
      routes: '/posts/网鼎杯-2020-半决赛-faka'
      views: never
    }
    'pages/posts/网鼎杯-2020-玄武组-SSRFMe.md': {
      routes: '/posts/网鼎杯-2020-玄武组-SSRFMe'
      views: never
    }
    'pages/posts/网鼎杯-2020-白虎组-PicDown.md': {
      routes: '/posts/网鼎杯-2020-白虎组-PicDown'
      views: never
    }
    'pages/posts/网鼎杯-2020-青龙组-notes.md': {
      routes: '/posts/网鼎杯-2020-青龙组-notes'
      views: never
    }
    'pages/posts/网鼎杯2018-Unfinish.md': {
      routes: '/posts/网鼎杯2018-Unfinish'
      views: never
    }
    'pages/posts/羊城杯-2020-Blackcat、.md': {
      routes: '/posts/羊城杯-2020-Blackcat、'
      views: never
    }
    'pages/posts/羊城杯-2020-Easyphp2.md': {
      routes: '/posts/羊城杯-2020-Easyphp2'
      views: never
    }
    'pages/posts/羊城杯-2020-EasySer.md': {
      routes: '/posts/羊城杯-2020-EasySer'
      views: never
    }
    'pages/posts/羊城杯2020-easyphp.md': {
      routes: '/posts/羊城杯2020-easyphp'
      views: never
    }
    'pages/posts/蓝帽杯-2021-One-Pointer-PHP.md': {
      routes: '/posts/蓝帽杯-2021-One-Pointer-PHP'
      views: never
    }
    'pages/posts/解密网站.md': {
      routes: '/posts/解密网站'
      views: never
    }
    'pages/posts/高明的黑客.md': {
      routes: '/posts/高明的黑客'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
